"""Shared state schema for the AI Analyst Agent workflow.

This module defines the TypedDict that maintains state across all agents
in the LangGraph workflow, ensuring consistent data flow and type safety.
"""

from typing import TypedDict, Any, List, Dict


class AgentState(TypedDict):
    """Shared state container for the multi-agent workflow.
    
    This TypedDict defines the structure of data that flows between agents:
    - question: User's natural language query
    - plan: Analysis plan generated by planner agent
    - sql: SQL query generated by SQL agent
    - result: Query results as list of dictionaries
    - insights: Business insights from analysis agent
    - chart_path: File path to generated visualization
    - chart_type: Type of chart generated (bar, line, scatter, none)
    """
    question: str  # User's original question
    plan: str  # Analysis plan from planner
    sql: str  # Generated SQL query
    result: List[Dict[str, Any]]  # Query results
    insights: str  # Business insights
    chart_path: str  # Path to saved chart HTML
    chart_type: str  # Chart type (bar, line, scatter, none)